cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #363016
selection_background  #d1c6a1
url_color             #e0c64b

color0   #131313
color1   #e14877
color2   #93d66e
color3   #dbb17b
color4   #a48d20
color5   #a8984e
color6   #e0c64b
color7   #abb2bf
color8   #5c6370
color9   #e05f8a
color10  #a5e086
color11  #e8c597
color12  #e9d488
color13  #967437
color14  #7f7b34
color15  #ffffff
